# Generated by Django 2.1.2 on 2018-11-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wuxiandjango',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelname', models.TextField()),
                ('author', models.TextField()),
                ('novelid', models.TextField()),
                ('noveltype', models.TextField()),
                ('novelsize', models.TextField()),
                ('downloadnum', models.TextField()),
                ('novelurl', models.TextField()),
                ('imgurl', models.TextField()),
                ('txtdownload', models.TextField()),
                ('zipdownload', models.TextField()),
                ('simplyintroduce', models.TextField()),
            ],
        ),
    ]
